version: '3.8'

services:
    flowise:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: flowise-backend
        restart: always
        ports:
            - '3000:3000'
        env_file:
            - .env
        environment:
            - PORT=3000
            - DATABASE_HOST=${DATABASE_HOST}
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - ~/.flowise:/home/node/.flowise
